CREATE DATABASE GRAPHIC_MASTER;
USE GRAPHIC_MASTER;

CREATE TABLE MATERIA_PRIMA (
	ID_PRODUTO int(11) NOT NULL AUTO_INCREMENT,
	NOME_MP varchar(64) CHARACTER SET utf8 NOT NULL,
	VALIDADE date NOT NULL,
	UNIDADE varchar(10) CHARACTER SET utf8 NOT NULL,
	VALOR decimal(10, 2) NOT NULL,
	QTD_ESTOQUE int(11) NOT NULL,
	ID_FORNECEDOR int(11) NOT NULL,
	PRIMARY KEY (ID_PRODUTO),
	FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

INSERT INTO MATERIA_PRIMA(ID_PRODUTO, NOME_MP, VALIDADE, UNIDADE, VALOR, QTD_ESTOQUE, ID_FORNECEDOR) VALUES
(1, 'PAPEL', '2020-01-10', 'KG', 100.00, 40, 1),
(2, 'CANETA', '2020-03-15', 'UN', 2.00, 15, 2),
(3, 'LÁPIS', '2020-05-25', 'UN', 1.00, 50, 3);